### DISCUSSION TITLE
How to self host using HA replicated ClickHouse

### DISCUSSION THREAD

**Discussion by andreeib** [openmeterio/openmeter#3050] [General]
Hello, 

I'm using OpenMeter to collect GPU compute allocation in a hosting platform, currently it's a MVP so I self host. So far the experience with OpenMeter has been great, it just lacks slightly on docs, for example It's not clear how I can run self hosted in a high availability setup.

I installed ClickHouse and ClickHouseKeeper using altinity-clickhouse-operator and configured it with 3 replicas each:
```
apiVersion: "clickhouse-keeper.altinity.com/v1"
kind: ClickHouseKeeperInstallation
metadata:
  name: chk
  namespace: ${var.namespace}
spec:
  configuration:
    clusters:
      - name: ${var.cluster_name}
        layout:
          replicasCount: 3
...
---
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: chi
  namespace: ${var.namespace}
spec:
  configuration:
    zookeeper:
      nodes:
        - host: keeper-chk
          port: 2181

    clusters:
      - name: ${var.cluster_name}
        layout:
          replicasCount: 3
...
```

I created a database:
`CREATE DATABASE IF NOT EXISTS ${var.db_name} ON CLUSTER ${var.cluster_name};`

Then installed OpenMeter Helm chart:
```
clickhouse = {
  enabled = false
    operator = {
      install = false
    }
}
config = {
  aggregation = {
    clickhouse = {
      address  = "${var.clickhouse_host}:${var.clickhouse_port}"
      username = var.clickhouse_username
      password = var.clickhouse_password
      database = var.clickhouse_database
     }
  }
}
...
```

Now as expected `GET /api/v1/meters/{meterIdOrSlug}/query` requests return inconsistent results based on what ClickHouse node it hits.

How can run OpenMeter with replicated ClickHouse?
Should I manually create a `ReplicatedMergeTree` table?

Thank you
