### ISSUE TITLE
Refactor Kafka Connect configuration

### ISSUE THREAD

**Issue by sagikazarmark** [openmeterio/openmeter#230]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/openmeterio/openmeter/issues) for an issue that matches the one I want to file, without success.

### Problem Description

#229 refactors Kafka Connect, but I believe there is more room for improvement.

The configuration feels a bit "disorganized" at the moment.

I'd also note that we probably do not want to use this feature in production, but want to manually configure Kafka Connect (I may be wrong about that).

### Proposed Solution

I can imagine two potential routes, both involve supporting multiple connectors.

The advantage of supporting multiple connectors is that we can experiment with different configurations without breaking existing ones.

Option one is to allow passing raw connector configuration:

```yaml
sink:
  kafkaConnect:
    enabled: true
    connectors:
      - name: clickhouse
        config:
          connector.class: "com.clickhouse.kafka.connect.ClickHouseSinkConnector"
          database: "openmeter"

          # ...
```

The downside of this solution is that we have no way to validate the configuration.

An alternative solution would be adding config schema for supported connectors (currently only clickhouse anyway):

```yaml
sink:
  kafkaConnect:
    enabled: true
    connectors:
      - name: clickhouse
        type: clickhouse
        config:
          database: "openmeter"

          # ...
```

Although option two is a bit more work, I probably prefer that for the moment because it makes misconfiguration harder.
