### ISSUE TITLE
Benthos schedule input does not exhaust non-batch inputs

### ISSUE THREAD

**Issue by sagikazarmark** [openmeterio/openmeter#688]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/openmeterio/openmeter/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/openmeterio/openmeter/issues/new/choose) without success.

### OpenMeter Version

v1.0.0-beta.53

### Expected Behavior

When wrapping a non-batch input in `schedule` input, only one document is being read from the input instead of reading all.

### Actual Behavior

All documents should be read

### Steps To Reproduce

```yaml
input:
  schedule:
    interval: "10s"
    input:
      sql_select:
        driver: postgres
        dsn: postgres://postgres:postgres@service_a:5432/service_a?sslmode=disable
        table: usage
        columns:
          - id
          - realm_id
          - subject
          - time
        where: time >= ?

        # Interval is 10 seconds, but we go back 15 seconds to make sure no events are missed.
        # Deduplication should take care of duplicate events
        # Tweak this based on your needs (ie. your priority of duplicated event ingestion vs potentially missed events)
        args_mapping: 'root = [ (now().ts_unix() - 15).ts_format(format: "2006-01-02 15:04:05", tz: "UTC") ]'

```

### Additional Information

Workaround: use [generate](https://www.benthos.dev/docs/components/inputs/generate#examples) input with `sql_select` processor and `unarchive` processor.

Also see https://github.com/benthosdev/benthos/discussions/2314
